services:
  database:
    image: mysql:9
    user: "0:0"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: test
    ports:
      - "127.0.0.1:3306:3306"
    command: --bind-address=0.0.0.0
    volumes:
      - MYSQL_DATA:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:z
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  MYSQL_DATA: