spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}
logging.level.org.springframework.security=DEBUG

front-end.url=${FRONT_END_URL:http://localhost:5173}