CREATE TABLE IF NOT EXIST produto(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    descricao VARCHAR(80),
    possuiValidade TINYINT NOT NULL,
    qtdMinAlert INT NOT NULL
);

CREATE TABLE IF NOT EXISTS transacoes(
    id INT AUTO_INCREMENT PRIMARY KEY,
    valor DOUBLE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    dataCriacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);