
spring.application.name=notification

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://database:3306/test
spring.datasource.username=root
spring.datasource.password=


spring.jpa.show-sql=true

server.port=${PORT:8081}

spring.rabbitmq.host=rabbitmq

spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nomes para nossa Exchange e Queue
app.rabbitmq.exchange=logs.direct
app.rabbitmq.queue=logs.queue
app.rabbitmq.routingkey=logs.routingkey

spring.rabbitmq.queue.name=notification-queue