
spring.application.name=notification

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=kore
spring.rabbitmq.password=kore

spring.rabbitmq.queue.name=notification-queue

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://database:3306/test
spring.datasource.username=root
spring.datasource.password=


spring.jpa.show-sql=true

server.port=${PORT:8081}